# Generated by Django 4.2 on 2025-02-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('photo1', models.ImageField(upload_to='')),
                ('photo2', models.ImageField(null=True, upload_to='')),
                ('photo3', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
