# Generated by Django 4.2 on 2025-02-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0002_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='target',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
