# Generated by Django 4.2 on 2025-02-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0003_alter_target_photo2_alter_target_photo3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='photo1',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
