# Generated by Django 4.2 on 2025-05-01 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0004_alter_target_photo1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=10)),
                ('weapon', models.CharField(max_length=10)),
                ('camera', models.IntegerField(max_length=10, null=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='target',
            name='photo3',
        ),
        migrations.AlterField(
            model_name='target',
            name='photo1',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='target',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
