# Generated by Django 4.2 on 2025-05-02 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0005_logs_remove_target_photo3_alter_target_photo1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='camera',
            field=models.IntegerField(null=True),
        ),
    ]
