# Generated by Django 4.2 on 2025-05-02 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0006_alter_logs_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
