# Generated by Django 4.2 on 2025-05-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0007_logs_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='screenshot',
            field=models.ImageField(blank=True, upload_to='media/screenshots'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='weapon',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='photo1',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='target',
            name='photo2',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
