# Generated by Django 4.2 on 2025-05-03 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0008_logs_screenshot_alter_logs_weapon_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logs',
            old_name='Date',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='logs',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='media/screenshots'),
        ),
    ]
