# Generated by Django 4.2 on 2025-05-03 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0009_rename_date_logs_date_alter_logs_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='screenshots/'),
        ),
    ]
