# Generated by Django 4.2 on 2025-05-03 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0010_alter_logs_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='target',
            name='photo1',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='target',
            name='photo2',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
